version: '3'
services:
    db:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - ./docker/db/dump:/dump
        environment:
            POSTGRES_DB: cv_maker
            MYSQL_ROOT_PASSWORD: postgres
            POSTGRES_PASSWORD: postgres
    # redis:
    #     image: redis
    #     ports:
    #         - "6379:6379"